# Site Settings
locale          : "pt-PT"
title           : "CodeWeek"
title_separator : "â€¢"
description     : "Aorem ipsum dolor sit amet elit sed lum tempor incididunt ut labore el dolore alg minim veniam quis nostrud ncididunt."
logo            : logo.png
url             : "https://codeweek.cesium.di.uminho.pt"
baseurl         :

# Google Analytics
analytics:

# Social
email        : "cesium@di.uminho.pt"
facebook     : "cesiuminho"
github       : "cesium"
gitlab       : 
google_plus  : 
instagram    : "cesiuminho"
linkedin     :
twitter      : "cesiuminho"
youtube      :

# Torneio
torneio-link : "http://www.cesium.di.uminho.pt/activities"


# Reading Files
encoding: "utf-8"
include:
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - CHANGELOG.md

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
